
# in this file, settings that are specific for a run on a dataset

# gives path to output folder
pipOutFold <- "OUTPUT_FOLDER/GSE71119_dediffSM_MFSM"

# full path (starting with /mnt/...)
# following format expected for the input
# colnames = samplesID
# rownames = geneID
# !!! geneID are expected not difficulted

# *************************************************************************************************************************
# ************************************ SETTINGS FOR 0_prepGeneData
# *************************************************************************************************************************

rnaseqDT_file <- "/mnt/ed4/marie/other_datasets/GSE71119/20.09_prepData/GSE71119_countDT_allcond.Rdata"
my_sep <- "\t"
# input is Rdata or txt file ?
# TRUE if the input is Rdata
inRdata <- TRUE

# can be ensemblID, entrezID, geneSymbol
geneID_format <- "geneSymbol"
stopifnot(geneID_format %in% c("ensemblID", "entrezID", "geneSymbol"))

# are geneID rownames ? -> "rn" or numeric giving the column
geneID_loc <- "rn"
stopifnot(geneID_loc == "rn" | is.numeric(geneID_loc))


removeDupGeneID <- TRUE

# *************************************************************************************************************************
# ************************************ SETTINGS FOR 1_runGeneDE
# *************************************************************************************************************************

# labels for conditions
cond1 <- "dediffSM"
cond2 <- "MFSM"

# path to sampleID for each condition - should be Rdata
sample1_file <- "/mnt/ed4/marie/other_datasets/GSE71119/20.09_prepData/dediffLPSM_ID.Rdata"
sample2_file <- "/mnt/ed4/marie/other_datasets/GSE71119/20.09_prepData/MFSM_ID.Rdata"

# not clear what kind of data they provide; they just say "expression matrix generated by R"
# first thought that "DESeq2" should be used, but as it contains negative values, cannot apply
# fpkm -> so set inputDataType to "FPKM"

#inputDataType <- "DESeq2"
inputDataType <- "FPKM"
